data:
    train:
        audio_feature: /home/tlshen/av_scene_classify/data/feature/audio_features_data/train.hdf5
        video_feature: /home/tlshen/av_scene_classify/data/feature/video_features_data/train.hdf5
    cv:
        audio_feature: /home/tlshen/av_scene_classify/data/feature/audio_features_data/val.hdf5
        video_feature: /home/tlshen/av_scene_classify/data/feature/video_features_data/val.hdf5
    test:
        audio_feature: /home/tlshen/av_scene_classify/data/feature/audio_features_data/test.hdf5
        video_feature: /home/tlshen/av_scene_classify/data/feature/video_features_data/test.hdf5
    audio_norm: /home/tlshen/av_scene_classify/data/feature/audio_features_data/global_mean_std.npz
    video_norm: /home/tlshen/av_scene_classify/data/feature/video_features_data/global_mean_std.npz
    dataloader_args:
        num_workers: 1
        batch_size: 128

model_name: mid
model:
    num_classes: 10
    audio_emb_dim: 512
    video_emb_dim: 512
output_dir: experiments_1/mid

optimizer:
    type: Adam
    args:
        lr: !!float 1e-4
        weight_decay: !!float 1e-4

lr_scheduler:
    args:
        patience: 3
        factor: 0.1

epoch: 100
early_stop: 7
